### PR TITLE
Handle upgrades in API instead of dashboard

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by alxndrsn** [comment]
@estellecomment @SCdF any thoughts on what we should do with this?

**Comment by SCdF** [comment]
@alxndrsn I think we should merge it into master. If we're not comfortable having this around when we don't officially support it, we should merge it but hide it behind a feature toggle.

**Comment by SCdF** [comment]
@alxndrsn I've created this PR which is just the relevant changes: https://github.com/medic/medic-api/pull/187 I'll work on cleaning it up alongside https://github.com/medic/medic-webapp/pull/3750

If you think this is a good base we can delete this branch / pr

**Comment by SCdF** [comment]
Superceeded by https://github.com/medic/medic-api/pull/187

**Pull request closed without merging**
