### PR TITLE
remove district arg from message controller functions

### PR DESCRIPTION
**Pull request by alxndrsn**
This arg doesn't seem to do anything.

### CODE REVIEW

**Comment by mandric** [comment]
Anyone have a clue why that was there in the first place? That seems too weird.

**Comment by mandric** [comment]
Only thing I can think of is since we do authorization based on district. Looks like a placeholder.

**Comment by alxndrsn** [comment]
Seems to be equally pointless in `develop`.  @garethbowen any objections to merging this and applhing the same fix to `develop`?

**Comment by garethbowen** [comment]
Yeah that looks like a hangover from the old days when restricted users could access couch directly. Fire when ready.

**Comment by alxndrsn** [comment]
TODO: merge to `develop`

**Pull request merged**
